### PR TITLE
Fix/Final - Scope.go - Shorthanded by putting function into the utilities service

### PR DESCRIPTION
**Pull request by torch2424**
I simply placed the function into utilities, and updated our current code accordingly, this fixes the branch I screwed up, and also made the code alot cleaner

### CODE REVIEW

**Comment by torch2424** [comment]
Fixes #35 and Closes #28

**Comment by julianpoy** [comment]
Woot looking fabulous. Can I delete the old messed up branch? The last thing I notice is that we need $scope.go = go so that the html can use the go function as well. You did that in the old branch, but not in this new one. Otherwise, fantastic work, thanks for jumping on it and fixing this.

**Comment by torch2424** [comment]
Yup please delete that! And we don't even need that scope.go = go anymore, I devised a way to not even need that to begin with, now its just go("path") :D

**Comment by julianpoy** [comment]
The reason it is necessary is because html cannot access real functions in Angular. You have to have the function in the scope to be accessible. Take the create button on the my events page for example. It no longer works because $scope.go does not exist. Same thing for friends and for my events and more. The html needs to be able to access functions through the scope.

**Comment by julianpoy** [comment]
Also I noticed you stopped using $location.path(). That is essential to switching urls in AngularJS. You can't use window.location or location.href. Using those, you get errors like this one:

[Error] Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [["fn: $locationWatch; newVal: 19; oldVal: 18"],["fn: $locationWatch; newVal: 20; oldVal: 19"],["fn: $locationWatch; newVal: 21; oldVal: 20"],["fn: $locationWatch; newVal: 22; oldVal: 21"],["fn: $locationWatch; newVal: 23; oldVal: 22"]]
http://errors.angularjs.org/1.2.16/$rootScope/infdig?p0=10&p1=%5B%5B%22fn%3A%20%24locationWatch%3B%20newVal%3A%2019%3B%20oldVal%3A%2018%22%5D%2C%5B%22fn%3A%20%24locationWatch%3B%20newVal%3A%2020%3B%20oldVal%3A%2019%22%5D%2C%5B%22fn%3A%20%24locationWatch%3B%20newVal%3A%2021%3B%20oldVal%3A%2020%22%5D%2C%5B%22fn%3A%20%24locationWatch%3B%20newVal%3A%2022%3B%20oldVal%3A%2021%22%5D%2C%5B%22fn%3A%20%24locationWatch%3B%20newVal%3A%2023%3B%20oldVal%3A%2022%22%5D%5D
	completeOutstandingRequest (angular.js, line 4304)
	(anonymous function) (angular.js, line 4601)

**Comment by torch2424** [comment]
Ohhhhhh noooooooo :'( It was working for me, I'll fix it right now, how do I roll back @julianpoy

**Comment by torch2424** [comment]
I rolled back by commiting, and now I gotta figure out how to use $location in our go function. Will this work? http://stackoverflow.com/questions/19747830/how-do-i-pass-scope-from-controller-to-service-in-angularjs

**Comment by torch2424** [comment]
Or actually, can we use the .module thingy that's in all the other services?

**Comment by torch2424** [comment]
And could we access service functions in our HTML? Or does it not work like that?

**Comment by julianpoy** [comment]
This documentation actually would solve it all...
http://fdietz.github.io/recipes-with-angular-js/controllers/sharing-code-between-controllers-using-services.html
I think that would allow $location use and would be using AngularJS properly. It may also allow the HTML to access it.

**Comment by torch2424** [comment]
@julianpoy Utitlities isnt created throughapp.factory, and after reviewing it, he never accesses the scope within the service itself, only the function :/

**Comment by torch2424** [comment]
After more reasearch, I think we may have to keep scope.go within the controller, I've been trying to make a go object, but then we would have to redo the views :/

**Comment by torch2424** [comment]
If anything I think we should just close this branch, and come back to it later, because I'm tried of wasting our time on this issue that preety much already works

**Comment by julianpoy** [comment]
Coolio. Go ahead and close, then delete.

**Pull request closed without merging**
