### PR TITLE
Scope.go - Shorthanded by putting function into the utilities service

### PR DESCRIPTION
**Pull request by torch2424**
I simply placed the function into utilities, and updated our current code accordingly

### CODE REVIEW

**Comment by torch2424** [comment]
Closes #28

**Comment by torch2424** [comment]
And sorry If I messed something up and pulled something wrong, seems like I may have :o

**Comment by julianpoy** [comment]
Ok so as far as closing issues, you simply comment "closes #such". There is no need to close the issue manually. Also, the issue shouldnt be closed until this is pulled in.

**Comment by julianpoy** [comment]
With pulling in the new-events branch, this branch is kinda very messed up. It might be best to create a new branch off of the current master, and put these changes manually into that new branch. Then we can pull it in without potentially messing things up.

**Comment by torch2424** [comment]
Oh man I'm messing up all over the place Sorry again dude, working on that right now!

**Comment by julianpoy** [comment]
Deleting this branch because its broken.

**Pull request closed without merging**
