### PR TITLE
Basic user search

### PR DESCRIPTION
**Pull request by julianpoy**
Searching is now enabled for name, username, phone and address1. This enables people to enter any part of one of those fields and results will be displayed for corresponding results ordered by name.

### CODE REVIEW

**Comment by julianpoy** [comment]
@torch2424 Please test and merge at your convenience.

**Comment by julianpoy** [comment]
Closes #32

**Comment by torch2424** [comment]
for some reason my git cannot pull or checkout from this branch :/

**Comment by torch2424** [comment]
FINALLY GOT IT NEVERMIND

**Comment by torch2424** [comment]
Issues:

1. Friend requests recieved links to events

2. Searching somethign and pressing enter just 404s

3. I guess I'm friends with ejkj

I'm preety sure im on the branch since terminal says:

torch2424@Gojira-Senpaii:~/Documents/Source/nudge-webapp$ git status
On branch search-users
Your branch is up-to-date with 'origin/search-users'.

I don't think we would want to merge this yet @julianpoy

**Comment by julianpoy** [comment]
1. Doesn't have to do with search-users. That has been fixed in branch user-profiles, and will be live in master when it is ready to pull in.
2. I don't quite understand. Seems serious. More description?
3. Search-users is for searching for people. It doesn't show who you are friends with.

You may be confused as to what this branch does. This is simply for search functionality. A search term returns ANY user as part of nudge.

**Comment by torch2424** [comment]
@julianpoy 

1. Cool, revision stuff is weird I wish they were all live as we made them, but beggars cant be choosers haha 

2. I entered "hi"  in the Friends > Seach search box and this was the inspect element console response : POST http://backend.nudgeit.co/users/string 404 (Not Found) And the browser shows nothing. i know the backend is not down since I can log in and stuff

3. And yeah I figured, but I was just saying in case it was an unintended side effect. I dont like ejkj, I dont even know who he/she is

And yeah I may be misunderstanding what's going on, but I figured something would happen right?

**Comment by julianpoy** [comment]
I have since figured out why this stuff is going on. Its kind of humorous.
1. Yep, thats just how git works
2. The reason it was down is because the backend is on an old branch (the new backend branch that supports this branch has not been pulled in yet) text me when you want to test it and I'll flip the backend over to the other branch for testing. So yeah, it was up but it didn't know how to do that stuff since it was old.
3. The reason you are friends with ejkj is because that was a test name I was using and I sent you a friend request. Hahaha. I forgot that I did until I looked into the problem. Good thing is that will all be covered in the user-profiles branch (which, by the way, is ready for pull).

**Comment by torch2424** [comment]
Alright just texted you!

**Comment by torch2424** [comment]
Alright cool, now that it is up, I can succesfully search for people, though I cant find you, and I feel like we should have something say no people found if it cannot be found. I feel like the no people found i could be another thing, but I feel like this is ready to pull!

**Comment by julianpoy** [comment]
Alright Ill make an issue for displaying if no results are found.

**Pull request merged**
