### PR TITLE
No-Results message, renamed friends to people

### LINKED ISSUE #39: Display if no search-users results were found
Currently the form does nothing if you search for a user and nothing is found. We should display a "nothing found" or something when the database returns a false set.

### PR DESCRIPTION
**Pull request by julianpoy**
Fixes #39 
Changes references to "friends" now known as "people", a more general term for a general page.

### CODE REVIEW

**Comment by julianpoy** [comment]
I decided to revert the change of naming, as the user profiles branch is currently working on that section. I will instead create an issue for it so it may be handled at a later time.

**Comment by torch2424** [comment]
Wait, so want me to test this or...?

**Comment by julianpoy** [comment]
Not much to test, but yeah. Test and merge.

**Comment by julianpoy** [comment]
Ive tested this and Im merging it.

**Pull request merged**
