### PR TITLE
User profile styling. Add, accept and decline friends. Refurbished friends page.

### PR DESCRIPTION
**Pull request by julianpoy**
This pull is focused on basic functionality of the following:

User profiles /user/:id now has some basic styling.
You can now send a friend request from a user's profile page.
The friends page now accurately displays all of the information currently returned from the database. You can see current friends, as well as pending friend requests and requests to you.
You can now accept or decline friends if they have requested you as a friend.

### CODE REVIEW

**Comment by julianpoy** [comment]
Closes #20

**Comment by julianpoy** [comment]
@torch2424 Do you want to take a look at the code and let me know if you spot anything fishy?

**Comment by torch2424** [comment]
Looking right now!

**Comment by torch2424** [comment]
Okay so I can defiinitely see other people's profiles which is awesome!, and by going to user/id (where id is a number near 43) I can see different users! And I can see my firends, but I dont see anything to request friends, and I cannot test my pending friend requests or outing requests

**Comment by julianpoy** [comment]
The backend has to be switched to this branch for any functionality for this. Text me when you wish to test this branch and I'll flip the toggle.

**Comment by torch2424** [comment]
After testing this, I still did not see the ability to request friends or pedning requests or anything like that last night @julianpoy

**Comment by julianpoy** [comment]
Last night you had me switch the backend to the search-users branch which doesn't contain the necessary code to support this. It is currently back on the master branch. If you need to test this to pull, load url 1 and then 2 in your browser. This flips the backend to the correct branch and then pulls from the branch.
http://backend.nudgeit.co/update.php?git=checkout&name=add-friend
http://backend.nudgeit.co/update.php?git=pull

Cool, right? Programmed that little bit myself.

**Comment by torch2424** [comment]
Dude I love this backend switcher, that's intense haha! and I can confirm this is now working, pulling in...

**Comment by torch2424** [comment]
Awwee cuh can't automatically merge, I give you permission to merge it, I dont know what to do haha

**Comment by julianpoy** [comment]
Our first non-automatic merge. I'll work on merging this code tonight.

**Comment by julianpoy** [comment]
This has been merged manually into master. Now closed.

**Pull request closed without merging**
