### PR TITLE
Unreachable

### PR DESCRIPTION
**Pull request by torch2424**
Catches Server errors when trying to login or join. Alerts the user and displays the error code in the console.

### CODE REVIEW

**Comment by julianpoy** [comment]
These changes should be applied every time a request to the backend is made.
Issue #11.

**Comment by torch2424** [comment]
Could you elaborate a bit more? want me to catch more errors, because as of right now, I'm preety positive that is what it does

**Comment by julianpoy** [comment]
These commits look okay. I think you're confused about what I meant.
I'll show/explain this more when we work tomorrow.

**Comment by julianpoy** [comment]
I didn't mean to catch more errors. I meant that we are only catching these errors in the login.js and join.js. There are many many more places that we access the backend. For example, in the https://github.com/Kondeo/nudge-webapp/blob/master/app/scripts/controllers/friends.jsL23

**Comment by julianpoy** [comment]
I rolled back the commit. Please use git pull when in the repository directory to pick up the new changes.

**Pull request merged**
