### PR TITLE
New events page - basic

### PR DESCRIPTION
**Pull request by julianpoy**
This is a basic starter new events page. It is fully functional for what it does. Later on we can implement description and more fields.

### CODE REVIEW

**Comment by julianpoy** [comment]
@torch2424 Please review this code for bugs, test it, and if it is acceptable merge the request. Thanks.

**Comment by julianpoy** [comment]
Closes #30

**Comment by torch2424** [comment]
Testing right now!

**Comment by torch2424** [comment]
Issues:

1. Events > Create Does not work, but Events > MyEvents > Create does

2. Required Fields Are not specified with an *

Want me to merge this still? and then I can go in and fix it?

**Comment by torch2424** [comment]
@julianpoy

**Comment by julianpoy** [comment]
I'll do those fixes in a moment. I was planning on fixing 1 in another pull, but it makes more sense to do it here.

**Comment by julianpoy** [comment]
There we go. All fixed.
Closes #17

**Comment by torch2424** [comment]
Alright! Rad so the two things fixed for me, but now I get there error:

SyntaxError: Unexpected token S
    at Object.parse (native)
    at fromJson (http://localhost:9000/bower_components/angular/angular.js:1078:14)
    at defaults.defaults.transformResponse (http://localhost:9000/bower_components/angular/angular.js:7317:18)
    at http://localhost:9000/bower_components/angular/angular.js:7292:12
    at Array.forEach (native)
    at forEach (http://localhost:9000/bower_components/angular/angular.js:323:11)
    at transformData (http://localhost:9000/bower_components/angular/angular.js:7291:3)
    at transformResponse (http://localhost:9000/bower_components/angular/angular.js:7963:17)
    at wrappedCallback (http://localhost:9000/bower_components/angular/angular.js:11319:81)
    at http://localhost:9000/bower_components/angular/angular.js:11405:26angular.js:9778 (anonymous function)angular.js:7216 (anonymous function)angular.js:11322 wrappedCallbackangular.js:11405 (anonymous function)angular.js:12412 Scope.$evalangular.js:12224 Scope.$digestangular.js:12516 Scope.$applyangular.js:8204 doneangular.js:8412 completeRequestangular.js:8351 xhr.onreadystatechange

In the inspect element elent console

This can be solved by entering a category, but A category is not a required field. So I think this is the last issue before we can pull this mother in

**Comment by julianpoy** [comment]
Ah. That has to dow with the backend not liking having an empty field.

**Comment by julianpoy** [comment]
The problem should now be fixed via a database patch. The database required the field to not be null, however now it can handle that. This should be completely ready for pulling in.
This branch requires the backend to be on the "master" branch. You can switch the backend to that branch using url 1 and then 2.
1. http://backend.nudgeit.co/update.php?git=checkout&name=master
2. http://backend.nudgeit.co/update.php?git=pull

**Comment by torch2424** [comment]
I'll check this out later!

**Comment by torch2424** [comment]
Can confirm everything works! pulling in now!

**Pull request merged**
