### PR TITLE
Logout Page/Functionality

### PR DESCRIPTION
**Pull request by torch2424**
Pressing Logout while Logged in, will now successfuly delete your cookie, and log you out, and return you to the homepage

### CODE REVIEW

**Comment by torch2424** [comment]
Sorry to assign you this yo! You dont have to feel like when we assign eachother stuff were making eachother do it haha

**Comment by torch2424** [comment]
Closes #26

**Comment by julianpoy** [comment]
To be clear, is there still work to be done on this that you'd like me to do? Im confused if you assigned it to me to finish the work or to do the pull request.

**Comment by torch2424** [comment]
Naw, @julianpoy I just wanted you to pull it in, it all wors last time I tested it!

**Comment by julianpoy** [comment]
Coolio. Will test.

**Pull request merged**
